### ISSUE TITLE
Update and select treat column names differently

### ISSUE THREAD

**Issue by tapir** [go-pg/pg#1022]
The model I use for the sake of example
```Go
type Server struct {
	tableName  struct{} `sql:"mydb.servers"`
	ID         int      `sql:"type:integer,pk"`
	NextIPv4   string   `sql:"next_ipv4,type:varchar(18),notnull"`
	NextIPv6   string   `sql:"next_ipv6,type:varchar(43),notnull"`
	Enabled    bool     `sql:"type:boolean,notnull"`
}
```

This  code works perfectly for the model above
```Go
if err := tx.Model(&servers).
	Column(
		"server.id",
		"server.next_ipv4",
		"server.next_ipv6",
	).
	Where("\"server\".enabled=?", true).
	Select(); err != nil {
	return err
}
```

While the one below gives the error ```http: panic serving [::1]:34490: can't find column=server."next_ipv4" in model=Server```
```Go
if _, err := tx.Model(&servers).
	Column(
		"server.next_ipv4",
		"server.next_ipv6",
	).Update(); err != nil {
	return err
}
```

However if I do it like below it works OK.
```Go
if _, err := tx.Model(&servers).
	Column(
		"next_ipv4",
		"next_ipv6",
	).Update(); err != nil {
	return err
}
```

Is this the expected behaviour?

**Comment by vmihailenco** [comment]
That is inconsistent and confusing, but yes - that is an expect behavior.

In SELECT `Column("server.id")` tries to find a relation `server` with column `id` and if that fails it fallbacks to just quoting the `server.id` hoping for the best.

In UPDATE `Column("server.id")` tries to find a relation `server`  and does not fallback to quoting since:
- AFAIR server.id is invalid in update
- there is no value to update `server.id` anyway unless go-pg supports `server.id`

I guess go-pg could be smart enough to recognize that `server.id` is a column in current model, but I don't aim to hide SQL warts/peculiarities from the user. go-pg aim is to help writing SQL - not to hide/abstract SQL from the user.

**Comment by tapir** [comment]
Fair enough. Thanks
