### ISSUE TITLE
How to save a recordset to a map?

### ISSUE THREAD

**Issue by dxvgef** [go-pg/pg#1121]
Can I receive a recordset with `[]map[string]interface{}`? Or add a `ScanHook` to let me handle the recordset myself?

```go
var result map[string]interface{}
pg.Model(&struct{}).Select(&result)
```

**Comment by lyw1995** [comment]
像这样吗? 
![image](https://user-images.githubusercontent.com/13196763/53072999-c235a800-3521-11e9-87ea-d220aeae96bf.png)

**Comment by vmihailenco** [comment]
Scanning into `map[string]interface{}` is not possible because go-pg receives `[]byte` and does not know the underlying Go type. Best we could do is decoding into `map[string][]byte` but that is of limited usability.

**Comment by maxless** [comment]
@vmihailenco In libpq you can get the type OIDs for all Postgres types through PQftype() call. Can you implement the same thing?

```
Oid PQftype(const PGresult *res, int column_number);
``

Basically, is there any way to run select query without defining struct for each query result? This makes it significantly more painful if you just want to select some data and pass it along without any or small modification.

**Comment by vmihailenco** [comment]
I believe that is only only available if you use prepared statements.

**Comment by maxless** [comment]
@vmihailenco 
I don't think so.

I've been using Postgres driver for a different language as a reference which I've maintained at one point (I'm not the author). libpq documentation states that you need to use PQprepare() to make a prepared statement. But the driver code does not have that call anywhere, only PQexec():

https://github.com/maxless/npostgres/blob/master/npostgres/postgres.c

And PQftype() works correctly since that is what allows the higher level code to correctly gain the type info for conversion.

**Comment by vmihailenco** [comment]
Indeed, it seems to be always available.
