### ISSUE TITLE
Selecting parts of a relation

### ISSUE THREAD

**Issue by Lallassu** [go-pg/pg#1272]
Is there a way to select specific parts of a nested model with the ORM?

Example:
I want to select all users with corresponding books but I want to filter only a few attributes from the book struct (I want to leave out 'Content' as an example).

If I have two structs likes this:
```
type User struct {
    Id int
    Name string
    Books []*Book
}

type Book struct {
    Id int
    Name string
    Content string
}
``` 

Doing `db.Model(&users).Select()` will get my books but with content. How can I instead get all users with all books but leave out the "Content" in the books array?

The corresponding JSON representation of what I'm asking is:
```
{
 Id: 1,
 Name: "User1",
 Books: [
      { 
        Id: 1,
        Name: "book1",
        Content: "This is a a huge text of the book....",
      }...
````

Instead I would like to get this:
```
 Id: 1,
 Name: "User1",
 Books: [
      { 
        Id: 1,
        Name: "book1",
      }...
```

**Comment by Lallassu** [comment]
ApplyFunc()

**Comment by dougwinsby** [comment]
Just to clarify, I believe @Lallassu is referring to the apply function of the `.Relation()`:

`Relation("Profiles", func(q *orm.Query) (*orm.Query, error)...`

This is normally used to filter by related columns (with a `.Where()`), but because the apply function returns a Query, it could also use `.Columns()` to limit the included columns (not tested by me).

As mentioned in the [Columns names](https://github.com/go-pg/pg/wiki/Writing-Queries#column-names) section of the wiki, you can also limit a relation to a single column with:

`Relation("Author.id")`

I've experimented with adding additional `Relation()` functions (on the same table) to get more columns, and it appears to work (but not sure it's recommended):

`Relation("Author.id").Relation("Author.name")...`

I'll use this apply function method in the future.
