### ISSUE TITLE
unexpected EOF on client connection with an open transaction

### ISSUE THREAD

**Issue by ernsheong** [go-pg/pg#1276]
I ran into the above error while trying to do UPDATE-heavy batch job on a DB with few rows (100-200).

There was no code error whatsoever, the job essentially hung and did not terminate.

Error message in the DB:
`unexpected EOF on client connection with an open transaction`

Any idea why this happened and how to mitigate it?

**Comment by vmihailenco** [comment]
No ideas here - we need a reproducer to move forward.

**Comment by Kangaroux** [comment]
@vmihailenco I'm experiencing the same issue which is causing my tests to sometimes fail, sometimes the connection is dropped several times. Do you want me to open a new issue?

EDIT: I assumed the issue was because of the EOF since it always showed up in the db log where an error occurred but it ended up being a race condition with how the tests are ran and unrelated to the EOF error. With that being said I'm wondering if this might be due to multiple goroutines using the same db connection

**Comment by vmihailenco** [comment]
@Kangaroux with minimal reproducible example - yes.
