### ISSUE TITLE
GO-PG Model Dependency and Microservices

### ISSUE THREAD

**Issue by asvsfs** [go-pg/pg#1576]
Hi Guys, 

When having multiple distinct services with models related to each other how should one handle the relations?

Post service shouldn't directly depends on user package
```
/* post.go - post package */
type Post struct {
    Text string `pg:"text"`
    User *User `pg:"user"`
}
/* user.go - user package */
type User struct {
    ....
    Posts *[]Post
}
```

with go-pg i have to add a pointer to User model inside the Post model definition which means importing User package this could end up in cyclic dependency or wrong architecture.

**Comment by SoftTacos** [comment]
This isn't a go-pg issue. What helped me resolve this issue is drawing a picture of all the imports and how they work, eventually realized that all the "primary" models/struct shouldn't be allowed to possess another model. You then need to have a separate "relations" directory that has structs which embed the primary model(ie: User or Post) and then establishes a named "has a" relationship. So you'd need a struct that embeds User, and has the field Posts *[]Post.

Google something like "golang object model relationships avoiding import cycles" for more info.

**Comment by vmihailenco** [comment]
What @SoftTacos said :+1:
