### ISSUE TITLE
ForEach - supporting maps or an inverse of discard_unknown_columns

### ISSUE THREAD

**Issue by JordanHitchman** [go-pg/pg#1881]
I have a unique use case ​where I have a core model and I need to be able to support joining additional columns from either the same table or different tables. Other than the core table, clients are likely to have the same
tables, but the inner workings of those tables will differ, for example; column names and types. Some clients may have a load of aggregate fields for example.

In terms of querying, this is fine, I generate a set of rules based on the schema per client and validate against that.

_I can go into more detail about the use case if it helps._

My question is two-part, is it possible to allow ForEach to support a map? So I can simply define a function that can take as input a single map argument, which I can do for Select but not ForEach.

Alternatively, and my preference, is it possible to have a custom tag that is the inverse of the discard_unknown_columns tag? 

Here's an example of my suggestion -

```
user struct {
	tableName struct{} `pg:"user,keep_unknown_columns"`
	UserID    string   `pg:"user_id,pk"`
	FirstName string   `pg:"first_name"`
	LastName  string   `pg:"last_name"`
	Email     string   `pg:"email_address"`
	AdditionalData map[string]interface{} `pg:"unknown_columns"` 	
}
```

```
func getUser() error {
	//construct some query


	return query.ForEach(func(u *user) error {
		//do something - send over gRPC/RabbitMQ for instance
	})
}
```

**keep_unknown_columns** might be redundant here since if the model doesn't have discard_unknown_columns, you could check a model has the **unknown_columns** tag before returning an error.

**Comment by elliotcourant** [comment]
The `unknown_columns` idea is interesting, but with the way queries are built the query would need to be `SELECT * FROM ...` or `SELECT "tableName".* FROM "tableName"...` which would leave column names intact from the table. This would mean it would be very hard for the ORM to determine which table a column was coming from in the result of a query if you were doing a join with any other tables and if there were any columns that were named in such a way that would conflict with another column, or in such a way that they could be mistaken as another column in the same query. The ORM would need to make **many** assumptions to support such a query. 
However I believe you could make something work by implementing the ColumnScanner interface on your object (shown below). This would allow you to implement the desired logic on your own for your use case; and makes it so that the ORM is not making these assumptions for you. 

https://github.com/go-pg/pg/blob/c9ee578a38d6866649072df18a3dbb36ff369747/orm/orm.go#L13-L20


I cannot speak to the foreach part, this seems a bit like two things in a single issue and maybe should be two separate issues?

**Comment by JordanHitchman** [comment]
@elliotcourant Yeah, I prefix all column names with the table name for that reason. I have various custom helper functions that extend go-pg.

Perhaps I'm mistaken, but if I implement **ColumnScanner**, it will only work for Select(), not ForEach(). Is that correct? If ForEach still makes a call to ScanColumn then this will work perfectly. I can define direct field mappings for known core fields and then add unknown fields to a map.

**Comment by vmihailenco** [comment]
@JordanHitchman I will see tomorrow if I can make go-pg's `ForEach` support maps.

Meanwhile you can try [Bun](https://bun.uptrace.dev/) with code like

```go
rows, err := db.NewSelect().Model((*Book)(nil)).Rows(ctx)
if err != nil {
	panic(err)
}
defer rows.Close()

for rows.Next() {
	m := make(map[string]interface{})
	if err := db.ScanRow(ctx, rows, &m); err != nil {
		panic(err)
	}
	fmt.Println(m)
}

if err := rows.Err(); err != nil {
	panic(err)
}
```
