### ISSUE TITLE
Order with subitem columns

### ISSUE THREAD

**Issue by matthewvalimaki** [go-pg/pg#309]
With #280 selecting subitems was fixed. In short we can now do `Column("book.*", "Authors", "Authors.Country")`. It seems to be impossible to do `Order("Authors.Country.Name") - documentation and code does not seem to support this. Is this correct?

I would like to be able to do `Order("Authors.Country.Name DESC")` and `Order("Authors.Country.Name, Authors.Country.Code DESC")`.

**Comment by vmihailenco** [comment]
I think it should be possible with query like this:

```
db.Model(&books).
  Column("book.*", "Authors", "Authors.Country").
  Relation("Authors", func(q *orm.Query) *orm.Query {
    return q.Order("authors__country.name, authors__country.code DESC")
  }).
  Select()
```

I am not fully sure about the column name `authors__country.name`, but you should be able to figure out correct name by inspecting generated query. Probably it is just `country.name`.

Supporting `Order("Authors.Country.Name")` is complicated, because order can include function calls like `Order("to_lower("Authors.Country.Name") NULLS FIRST")`. Parsing such statement is too much effort.

**Comment by matthewvalimaki** [comment]
Thanks @vmihailenco it worked.
