### ISSUE TITLE
Query result iterator

### ISSUE THREAD

**Issue by erizocosmico** [go-pg/pg#448]
Hi, first of all thanks for this great library.

I was reading the documentation and peeking at the code to see if there was any way to iterate over a query result but I found none. Did I miss something or is it in the roadmap?

I think it would be really helpful to have this feature, as sometimes you don't want to load a lot of records into memory when the result set is big or do the batching by hand every single time.

Thanks!

**Comment by vmihailenco** [comment]
I don't have a better way than doing it manually
- `WHERE id > 0 ORDER BY id ASC LIMIT 100`
- `WHERE id > 100 ORDER BY id ASC LIMIT 100`
- etc

I usually write such code manually every time I need it. I am not sure that writing a general helper is a good idea, because it is not obvious how many goroutines you want to process records or if you want to stop on first error or process all notices etc.

**Comment by erizocosmico** [comment]
I meant something like [`sql.Rows`](https://golang.org/pkg/database/sql/#Rows) in the standard library. But ok, no problem, can totally do it manually. 

Thanks!

**Comment by quexer** [comment]
- It would be great if go-pg could support result set iterator
- Just like any other db driver

**Comment by vmihailenco** [comment]
What is the use case of sql.Rows-like iterator? Not loading whole dataset into memory? AFAIK that is not possible with Postgres, because Postgres sends all data that was requested and it is just gets buffered somewhere else (Go buffered reader, OS buffer, pgbouncer buffer etc). You can't processes gigabytes of data with such iterator.

**Comment by overmesgit** [comment]
i can't but i do.

**Comment by zippoxer** [comment]
@vmihailenco 

I think having iteration is important. Iteration can really help in both those cases:

1. Delaying parsing and mapping of rows from Postgres to the models. Let's say I'm retrieving a million rows, and I want to iterate them on the application side until I found the one I'm looking for and then break.

If I found my row before the 1 millionth, then avoiding parsing & mapping the rest of the rows would save a lot of CPU time and memory (model structs consume much more than rows on the Postgres wire).

2. Avoiding conversion of `[]Model` to `[]ExposedModel`. Let's say I'm building an API or implementing an interface. I don't necessarily want to expose `Model` to clients. I will build `ExposedModel` which has similar or same fields as `Model` and only expose what I choose to. In this case, `pg-go` could help by allowing us to iterate the result set and convert `Model` to `ExposedModel` one by one, and by doing so, avoid allocating the `[]Model` slice which we don't use at all.

Can you guide me as to how you would do it if you were to add iterators to `go-pg/pg`?

**Comment by vmihailenco** [comment]
Did you see https://github.com/go-pg/pg/issues/448#issuecomment-318569074?

**Comment by zippoxer** [comment]
@vmihailenco Yes, I'm my reply is for comment #448 ;-)

My point is that yes, all the rows are loaded to memory anyway, but application-side models that go-pg populates consume much more memory than rows sitting on a Go buffered reader or OS buffer.

Don't you think so?
