### ISSUE TITLE
What's the best way to vendor-in go-pg/pg?

### ISSUE THREAD

**Issue by tapir** [go-pg/pg#640]
So this may be a shortcoming of Go instead of go-pg/pg but I wonder if you have solution that I don't know of.

What I basically do is that I have 2 services (separate Go projects) using the same database and a 3rd Go project (a library) that accepts pg.DB pointer as it's input to do some db maintenance.

I've used godep in all 3 projects and Go complains about pg.DB types not being compatible since all of them are vendored-in separately, for Go they are all different types.

I could use something like gopkg.in but it doesn't allow minor versions and it won't solve the problem with your internal libraries (internal, orm etc..) which are imported as "github.com/go-pg/pg/orm" etc. so when I do `go get gopkg.in/pg.v6` it will also fetch your master for the internal libraries.

edit: looks like gopkg.in doesn't allow internal libraries at all. it complains while fetching.

So I'm stuck. What's the best way of getting a fixed go-pg/pg version to be integrated to my projects?

**Comment by vmihailenco** [comment]
This is not a go-pg problem so you probably will get better answer somewhere else :)

AFAIK everything should work just fine as long as you have 1 vendor folder, i.e. all dependencies are saved once as late as possible in one of your projects.

Another possible solution is to define some interface and pass it instead of `*pg.DB` - https://github.com/go-pg/pg/blob/master/orm/orm.go#L20-L41
