### ISSUE TITLE
Why is Column() invalid for Insert()?

### ISSUE THREAD

**Issue by dxvgef** [go-pg/pg#642]
The `Column()` is invalid for `Insert()`
`Model(...).Column("...", "...").Insert()`
If I mark `sql:"-"` in the struct, I cannot query the field.
Why is `Column()` valid for `Update()`, but invalid for `Insert()`?

**Comment by vmihailenco** [comment]
It is valid - just not supported yet.

**Comment by dxvgef** [comment]
Why not?

**Comment by vmihailenco** [comment]
Overall it could be better if you split your model:

```
type Category struct {
    Id int
    Name string
}

type CategoryWithCount struct {
    Category `pg:",override"`
    ItemsCount int
}
```

And use `Category` to insert data and `CategoryWithCount` to select data. That is what I did in exactly one place where I needed it.

**Comment by dxvgef** [comment]
Understand, but I think it may be convenient for `Column()` to support `Insert()`

**Comment by vmihailenco** [comment]
The problem here is that there is `SelectOrInsert` and current convention is that `Select` respects `Column` and `Insert` does not. I don't an easy solution except adding specialized `InsertColumn` which is ugly and bloats API.

In following example we select user name by id or insert user to database:

```go
db.Model(&user).
    Column("name").
    Where("id = ?id").
    SelectOrInsert()
```
