### ISSUE TITLE
join on composite keys

### ISSUE THREAD

**Issue by wildan2711** [go-pg/pg#675]
I have two structs to save a `user` and a `friendship` status, like these:
```
type User struct {
	ID          int64     `json:"id"`
	UserName    string    `json:"user_name" sql:",unique"`
	Email       string    `json:"email" sql:",unique"`
	DisplayName string    `json:"display_name"`
	Created     time.Time `json:"created"`
	Modified    time.Time `json:"modified"`
}
```

```
type Friendship struct {
	UserID   int64          `json:"user_id" sql:",pk"`
	FriendID int64          `json:"friend_id" sql:",pk"`
	Status   status.Friends `json:"status"`
	Created  time.Time      `json:"created"`
	Modified time.Time      `json:"modified"`
}
```

And I want to achieve a query like this using go-pg:
```
SELECT *
FROM users u 
LEFT JOIN friendships f 
ON u.id = f.friend_id 
AND f.user_id = 2856445856
WHERE u.user_name = 'wildancok' ;
```

So it would join both tables one-to-one. How would I modify the struct(s) and construct the go-pg query to return the joined tables?

**Comment by wildan2711** [comment]
I tried something like:
```
data := new(User)
...
db.Model(data).
	Join("INNER JOIN friendships f ON \"user\".id = f.friend_id AND f.user_id = ?", currentUserID).
	Where("user_name = ?", data.UserName).
	Select()
```

modified the `User` struct to something like, (theoretically bad model):
```
type User struct {
	ID          int64     `json:"id"`
	UserName    string    `json:"user_name" sql:",unique"`
	Email       string    `json:"email" sql:",unique"`
	DisplayName string    `json:"display_name"`
	Created     time.Time `json:"created"`
	Modified    time.Time `json:"modified"`
	FriendID int64 `sql:"-" pg:"FriendID,fk:Friendship"`
	Friend   *Friendship	
}
```
I still don't quite understand the tags.. I'm sure those tags are wrong.

**Comment by julienkosinski** [comment]
I'm interested in understanding this too. :)
@vmihailenco

**Comment by vmihailenco** [comment]
Hi,

Following seems to work for me

```
package main

import (
	"time"

	"github.com/go-pg/pg"
)

type User struct {
	ID          int64     `json:"id"`
	UserName    string    `json:"user_name" sql:",unique"`
	Email       string    `json:"email" sql:",unique"`
	DisplayName string    `json:"display_name"`
	Created     time.Time `json:"created"`
	Modified    time.Time `json:"modified"`

	Friendship *Friendship
}

type Friendship struct {
	UserID int64 `json:"user_id" sql:",pk"`
	User   *User

	FriendID int64 `json:"friend_id" sql:",pk"`
	Friend   *User

	Created  time.Time `json:"created"`
	Modified time.Time `json:"modified"`
}

func main() {
	db := pg.Connect(&pg.Options{
		User: "postgres",
	})

	user := new(User)
	err := db.Model(user).Column("Friendship", "Friendship.Friend").Select()
	if err != nil {
		panic(err)
	}
}
```

**Comment by RainbowKatz** [comment]
Hi there.  Thanks for this package!

I just ran into a case for a composite key and wanted to report that ```go-pg``` DOES support composite primary keys via the ``` `sql:",pk"` ``` tag.  Perhaps you can add an example for this?

[Here](https://dba.stackexchange.com/questions/188995/composite-primary-keys-is-a-bad-practice) is a pretty good post about the topic with discussion and examples.

Basically, there are times when you can't just use an ```int``` ID as your primary key because you need to allow repeating columns but not a repeating COMBINATION of columns.  In the example given in the accepted answer in the post above, a student must be able to repeat in multiple rows to have multiple classes and a class must be able to repeat to have multiple students.  However, you cannot allow two rows to have the same combo of student and class together.  That's where a composite primary key comes in handy.

If you were to just use an ```int``` ID in the above example, you can't enforce uniqueness of the COMBINATION of columns as the ```int``` is the whole key and will always be unique and so all rows will be added regardless of other columns.  On the other hand, if you use ``` `sql:",unique"` ``` tags on those columns, then that field's value can't repeat in ANY other row, which is too restrictive.  A composite primary key is the only way to enforce the proper relationship in this case.

An example from the scenario above may look like this:

```
type ClassStudent struct {
    ClassID          int  sql:",pk"`
    StudentID        int  sql:",pk"`
    EnrollmentTxNo   int `sql:",unique"`
    EnrollmentDate   time.Date
}
```
So, this tag configuration would allow ```ClassID``` to repeat in multiple rows as well as ```StudentID``` (and ```EnrollmentDate```).  However, the COMBINATION of ```ClassID``` and ```StudentID``` cannot be repeated.  For contrast, I also included ```EnrollmentTxNo``` which is a transaction number specific to the combination of Class and Student and so should not be repeated in ANY row (hence the ``` `sql:",unique"` ``` tag.  However, ```EnrollmentTxNo``` would NOT be a suitable primary key on its own due to the lack of restriction that would introduce between ```ClassID``` and ```StudentID``` nor would it be a suitable part of the composite key as that would allow duplicate ```EnrollmentTxNo``` values in different rows.  So, in this particular case, the above would be the most suitable design which properly reflects all constraints and relationships, using ```go-pg``` tags.

Again, happy to report that ```go-pg``` supports composite primary keys by simply adding the ``` `sql:",pk"` ``` tag to multiple fields.  Each field with this tag becomes part of the composite key.  However, it would be nice to see an example of this in the docs.  Unless, of course, I missed it in which case I figure at least this could come up in a search and help someone with similar requirements.

Thanks again!
