### ISSUE TITLE
float64 with value 0 generates an SQL with NULL value instead of 0

### ISSUE THREAD

**Issue by tapir** [go-pg/pg#698]
I'm selecting a numeric field with a value 0 from a postgre 10 to a go type of float64. then I try to update the same row without changing anything and I get the error that the field is NULL whereas it shouldn't be. I've looked at the generated SQL and indeed instead of setting the value to "0" it tries to set it to NULL.

**Comment by siteshen** [comment]
There is a workaround:
```go
type Storage struct {
	ID     int64
	SomeID int64 `sql:",notnull"`
}
```

**Comment by vmihailenco** [comment]
Use `notnull` as was suggested.

**Comment by tapir** [comment]
Why is it treating 0 as NULL though? What if I wanted to update a numeric field with value 0?

**Comment by vmihailenco** [comment]
Then use `,notnull`. Readme says

```
All struct fields are nullable by default and zero values (empty string, 0, zero time) are marshalled as SQL NULL. sql:",notnull" tag is used to reverse this behaviour.
```

**Comment by 5k3105** [comment]
I think this is bad behavior. 
I have a Status table (simplified here):
(Id, UploadStart, UploadEnd, NumErrors)

Operation starts and Status record is inserted with UploadStart time.

If completed it will update UploadEnd and NumErrors on that same row (using Id).
If operation never completed, UploadEnd  and NumErrors will be NULL because it was not updated. 

This row needs to allow null in UploadEnd and NumErrors because it inserts as UploadStart only.
It also needs to allow zero in NumErrors because when (if) operation completes, UploadEnd and NumErrors will be updated. NumErrors as NULL or zero or number are all distinct values.

```go
	stat := Statusrec{
		UploadStart: time.Now(),
	}
	_, err := db.Model(&stat).Insert()
	statusId = stat.Id /// used later for update
```


```go
	stat := Statusrec{
		Id:        statusId,
		UploadEnd: time.Now(),
		NumErrors: num_errors,
	}
	_, err := db.Model(&stat).Column("upload_end", "num_errors").WherePK().Update()
```

For now, when NumErrors is updated as zero and db row says NULL, I believe this is false information.

**Comment by mewwts** [comment]
I also find this pretty weird.

I'd want to be able to have both `NULL`s and `0`s in an integer field. I don't understand how that's _not_ a common usecase?

**Comment by vmihailenco** [comment]
Use `sql.NullInt64`

**Comment by mewwts** [comment]
Thanks @vmihailenco!
