### ISSUE TITLE
Return interface on db.Begin()

### ISSUE THREAD

**Issue by cscatolini** [go-pg/pg#739]
Hello,

We are using go-pg in several of our projects and we always mock the database for unit tests. We need to make tests for methods that use transactions, but since `db.Begin()` does not return an interface we're not able to mock the database for these operations. 

Would you be willing to do this modification? If you'd like I could write a PR.  

Thanks in advance.

**Comment by vmihailenco** [comment]
Hi,

It would be acceptable to introduce 1 more interface for this purpose, but then we will likely have to add:
- Stmt interface instead of `*Stmt` to mock prepared statements
- Listener interface instead of `*Listener` to mock listeners
- Query interface instead of `*Query` to mock ORM queries

That is a lot and promotes interfaces everywhere in the API.

Could you instead write small wrapper like this:

type Tx interface {}

```
func dbBegin(db *pg.DB) (Tx, error) {
    return db.Begin()
}
```

And change `dbBegin` to return mocked transaction in the tests?

**Comment by cscatolini** [comment]
Indeed I was able to mock this way, but I had to do a huge workaround. I'd rather have interfaces everywhere in the API (Tx, Stmt, Listener and so on). Would you consider this for a future go-pg release?

**Comment by vmihailenco** [comment]
So far no, I don't think this feature is worth it.

TBH I don't see what will be the difference for you if go-pg returns `Tx` interface instead of `*Tx`. You still have to hijack the `*pg.DB` to return mocked transaction instead of a real one. So you need to create custom `DB` interface and while doing it you can change API from `(*Tx, error)` to `(YourTx, error)`.

**Comment by cscatolini** [comment]
The difference is that if go-pg returns a `Tx` interface I'll be able to pass on a mocked `Tx` object as long as it implements the interface contract.

This is exactly what I am doing with `pg.DB`. In this case you do return an interface so I can return a mocked object that implements it. This is also why I can't change the API to return `(YourTx, error)` instead of `(*Tx, error)`. If I do it, my DB mock no longer implements the DB interface.

**Comment by vmihailenco** [comment]
Okay, as I understand it there is some 3-rd party code that accepts `orm.DB` interface and you want to mock it without changing it. That is valid concern - I was just thinking that there is no much 3-rd party code that uses `orm.DB` except go-pg/sharding lib...

You said you are willing to submit a PR? If that is still true can you please do it with some example explaining how to mock a tx? Thanks in advance.
